/** @typedef {{
 *   borderActive: string,
 *   borderFocus: string,
 *   borderFocusVisible: string,
 *   cellFocusWithinBorder: string,
 *   ringFocus: string,
 *   ringFocusWithWidth: string,
 *   insertZoneFocus: string,
 *   controlFocus: string,
 *   textAccent: string,
 *   textAccentStrong: string,
 *   textAccentLight: string,
 *   textAccentFocus: string,
 *   bgAccent: string,
 *   bgAccentStrong: string,
 *   dragBorder: string,
 *   dragShadow: string,
 *   playbackGlow: string,
 *   pianoRollSelectionGlow: string,
 *   selectionShell: string,
 *   selectionRing: string,
 *   selectionBorder: string,
 *   pianoNoteIdle: string,
 *   pianoNoteSelected: string,
 *   pianoNoteActive: string,
 *   velocityBarFill: string,
 *   velocityBarFillPreview: string,
 *   durationTrackBg: string,
 *   durationBorder: string,
 * }} RowAccent */

/** Global interface accent — intentionally distinct from any row palette. */
/** @type {RowAccent} */
export const interfaceAccent = {
  borderActive: "border-accent",
  borderFocus: "border-accent-strong",
  borderFocusVisible: "",
  cellFocusWithinBorder: "",
  ringFocus: "",
  ringFocusWithWidth: "",
  insertZoneFocus: "focus-visible:ring-1 focus-visible:ring-focus-ring",
  controlFocus: "focus:border-focus-ring focus:ring-1 focus:ring-focus-ring",
  textAccent: "text-accent",
  textAccentStrong: "text-accent-strong",
  textAccentLight: "text-accent",
  textAccentFocus: "focus-visible:text-accent",
  bgAccent: "bg-accent",
  bgAccentStrong: "bg-accent-strong",
  dragBorder: "border-accent",
  dragShadow: "shadow-accent-drag",
  playbackGlow: "shadow-accent-playback",
  pianoRollSelectionGlow: "shadow-[0_0_0_2px_color-mix(in_srgb,var(--color-accent)_95%,transparent),0_0_4px_1px_color-mix(in_srgb,var(--color-accent)_85%,transparent),0_0_10px_2px_color-mix(in_srgb,var(--color-accent)_60%,transparent)]",
  selectionShell: "shadow-[0_0_0_1px_color-mix(in_srgb,var(--color-accent)_55%,transparent),0_0_8px_color-mix(in_srgb,var(--color-accent)_18%,transparent)]",
  selectionRing: "ring-1 ring-accent/28",
  selectionBorder: "border-accent/55",
  pianoNoteIdle: "border-accent/20 bg-accent/85 shadow-[inset_0_1px_0_color-mix(in_srgb,var(--color-text)_12%,transparent)]",
  pianoNoteSelected: "border-transparent bg-accent-strong",
  pianoNoteActive: "border-accent-strong bg-accent-strong shadow-accent-piano-active",
  velocityBarFill: "bg-[color-mix(in_srgb,var(--color-accent)_32%,transparent)]",
  velocityBarFillPreview: "bg-[color-mix(in_srgb,var(--color-accent)_56%,transparent)]",
  durationTrackBg: "bg-[color-mix(in_srgb,var(--color-accent)_16%,var(--color-surface))]",
  durationBorder: "border border-accent",
};

/** Row 1 accent — palette tokens live in semantic-theme.generated.css. */
/** @type {RowAccent} */
export const emeraldRowAccent = {
  borderActive: "border-row-accent-1",
  borderFocus: "border-row-accent-1-strong",
  borderFocusVisible: "",
  cellFocusWithinBorder: "",
  ringFocus: "",
  ringFocusWithWidth: "",
  insertZoneFocus: "focus-visible:ring-1 focus-visible:ring-row-accent-1-strong",
  controlFocus: "focus:border-row-accent-1-strong focus:ring-1 focus:ring-row-accent-1-strong",
  textAccent: "text-row-accent-1",
  textAccentStrong: "text-row-accent-1-strong",
  textAccentLight: "text-row-accent-1-soft",
  textAccentFocus: "focus-visible:text-row-accent-1-soft",
  bgAccent: "bg-row-accent-1",
  bgAccentStrong: "bg-row-accent-1-strong",
  dragBorder: "border-row-accent-1",
  dragShadow: "shadow-[0_0_10px_color-mix(in_srgb,var(--color-row-accent-1)_40%,transparent)]",
  playbackGlow: "shadow-[0_0_14px_color-mix(in_srgb,var(--color-row-accent-1)_55%,transparent)]",
  pianoRollSelectionGlow: "shadow-[0_0_0_2px_color-mix(in_srgb,var(--color-row-accent-1)_95%,transparent),0_0_4px_1px_color-mix(in_srgb,var(--color-row-accent-1)_85%,transparent),0_0_10px_2px_color-mix(in_srgb,var(--color-row-accent-1)_60%,transparent)]",
  selectionShell: "shadow-[0_0_0_1px_color-mix(in_srgb,var(--color-row-accent-1)_55%,transparent),0_0_8px_color-mix(in_srgb,var(--color-row-accent-1)_18%,transparent)]",
  selectionRing: "ring-1 ring-row-accent-1/28",
  selectionBorder: "border-row-accent-1/55",
  pianoNoteIdle: "border-row-accent-1-soft/25 bg-row-accent-1/85 shadow-[inset_0_1px_0_color-mix(in_srgb,var(--color-text)_12%,transparent)]",
  pianoNoteSelected: "border-transparent bg-row-accent-1-strong",
  pianoNoteActive: "border-row-accent-1-strong bg-row-accent-1-strong shadow-[0_0_12px_color-mix(in_srgb,var(--color-row-accent-1)_65%,transparent)]",
  velocityBarFill: "bg-[color-mix(in_srgb,var(--color-row-accent-1)_32%,transparent)]",
  velocityBarFillPreview: "bg-[color-mix(in_srgb,var(--color-row-accent-1)_56%,transparent)]",
  durationTrackBg: "bg-[color-mix(in_srgb,var(--color-row-accent-1)_16%,var(--color-surface))]",
  durationBorder: "border border-row-accent-1",
};
